name: Francis Borja
markdown: kramdown
permalink: /:title
paginate: 5
excerpt_separator: <!--excerpt-->
paginate_path: "/blog/page-:num"
include: ["_pages"]

#Google
google_analytics: UA-84144727-2
google_site_verification: iLcn0SOTj8DwWZ4p_P_h3J_lxE8i1ZikWIx4lthZuCY

#SEO
title: Francis Borja
description: Hello. My name is Francis and Francis means freedom.
logo: /assets/logomark-color.png

#Social
social:
  links:
    - https://twitter.com/freeingfrancis
    - https://instagram.com/freeingfrancis

url: https://francisborja.com
enforce_ssl: francisborja.com

# Post Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Twitter Cards
twitter_username: freeingfrancis
site_username: freeingfrancis
creator_username: freeingfrancis
author:
  twitter: freeingfrancis


# Stylesheets
sass:
  style: expanded
  deploy_style: compressed
  sass_dir: _sass



gems:
- activesupport
- addressable
- bundler
- bundler-unload
- coffee-script
- coffee-script-source
- concurrent-ruby
- executable-hooks
- fastercsv
- gem-wrappers
- github-pages
- github-pages-health-check
- html-pipeline
- io-console
- jekyll
- jekyll-avatar
- jekyll-coffeescript
- jekyll-default-layout
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-import
- jekyll-mentions
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-sass
- jekyll-sass-converter
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-swiss
- jekyll-titles-from-headings
- jekyll-watch
- json
- kramdown
- liquid
- listen
- mercenary
- mini_portile2
- minima
- minitest
- multipart-post
- net-dns
- net-telnet
- nokogiri
- octokit
- openssl
- paginate
- pathutil
- public_suffix
- rake
- rails
- rb-fsevent
- rb-inotify
- rdoc
- rouge
- ruby_dep
- rubygems-bundler
- rubygems-update
- rvm
- safe_yaml
- sass
- sawyer
- terminal-table
- test-unit
- thread_safe
- unicode-display_width
